import {
  ErButton,
  ErButtonGroup,
  ErIcon,
  ErCollapse,
  ErCollapseItem,
  ErAlert,
  ErTooltip,
  ErDropdown,
  ErDropdownItem,
  ErPopconfirm,
  ErMessage,
  ErNotification,
  ErMessageBox,
  ErInput,
  ErLoading,
  ErSwitch,
  ErSelect,
  ErOption,
  ErForm,
  ErFormItem,
} from "@toy-element/components";
import type { Plugin } from "vue";

export default [
  ErButton,
  ErButtonGroup,
  ErIcon,
  ErCollapse,
  ErCollapseItem,
  ErAlert,
  ErTooltip,
  ErDropdown,
  ErDropdownItem,
  ErPopconfirm,
  ErMessage,
  ErNotification,
  ErMessageBox,
  ErInput,
  ErLoading,
  ErSwitch,
  ErSelect,
  ErOption,
  ErForm,
  ErFormItem,
] as Plugin[];
